[ko]
  title = "Blazegrad's Blog"
  languageName = "한국어"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ko"

# [en]
#   title = "Blazegrad's Blog"
#   languageName = "English"
#   weight = 2
#   languagedir = "ltr"
#   contentdir = "content/en"

